name = "henry-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

workers_dev = true

[vars]
# GROQ_API_KEY set via: wrangler secret put GROQ_API_KEY

[[kv_namespaces]]
binding = "HENRY_KV"
id = "dd0a36cb7d854ae2b1da573bb535a6be"

[env.production]
name = "henry-proxy"

[env.staging]
name = "henry-proxy-staging"
